# Generated by Django 5.2.5 on 2025-08-24 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerusermodel_followering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerusermodel',
            name='followers',
        ),
        migrations.AlterField(
            model_name='customerusermodel',
            name='followering',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
