# Generated by Django 5.2.5 on 2025-08-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customerusermodel_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerusermodel',
            old_name='followering',
            new_name='following',
        ),
    ]
