# Generated by Django 5.2.5 on 2025-08-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_followering_customerusermodel_following'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('notifications', '0003_alter_notification_target_content_type_and_more'),
        ('posts', '0007_rename_create_at_like_created_at_alter_like_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUserModel',
            new_name='CustomUser',
        ),
    ]
