# Generated by Django 5.2.5 on 2025-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_created_at_alter_post_updated_at_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
