# Generated by Django 5.2.5 on 2025-08-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like_delete_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
