# Generated by Django 5.2.5 on 2025-08-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='author',
            new_name='actor',
        ),
    ]
